# generate_version.ps1 — Pre-build script that derives version from the latest git tag.
# Generates version.gen.h (C++ defines) and version.txt (update-check file).
# Only rewrites files when content changes to avoid unnecessary rebuilds.

$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot  = Split-Path -Parent $scriptDir

# Read version from latest git tag (e.g. "0.7.0").
$tag = git -C $repoRoot describe --tags --abbrev=0 2>$null
if (-not $tag) { $tag = "0.0.0" }
$version = $tag -replace '^v', ''
$parts   = $version.Split('.')
if ($parts.Count -lt 3) { $parts = @("0","0","0") }

$major = $parts[0]
$minor = $parts[1]
$patch = $parts[2]

# ── version.gen.h ──────────────────────────────────────────────────────────
$header = @"
// Auto-generated by generate_version.ps1 — do not edit.
#pragma once
#define PLUGIN_VERSION      "$version"
#define PLUGIN_VERSION_RC   $major,$minor,$patch,0
#define PLUGIN_VERSION_STR  "$version.0"
"@

$headerPath = Join-Path $scriptDir "version.gen.h"
$upToDate   = (Test-Path $headerPath) -and
              ((Get-Content $headerPath -Raw) -match ([regex]::Escape("PLUGIN_VERSION      `"$version`"")))
if (-not $upToDate) {
    $headerNorm = $header -replace "`r`n", "`n"
    [System.IO.File]::WriteAllText($headerPath, $headerNorm + "`n")
    Write-Host "generate_version: wrote $headerPath ($version)"
} else {
    Write-Host "generate_version: version.gen.h up to date ($version)"
}

# ── version.txt (repo root, for plugin update check) ──────────────────────
$versionTxtPath = Join-Path $repoRoot "version.txt"
$existingTxt    = if (Test-Path $versionTxtPath) { Get-Content $versionTxtPath -Raw } else { "" }
if ($existingTxt.Trim() -ne $version) {
    [System.IO.File]::WriteAllText($versionTxtPath, $version)
    Write-Host "generate_version: wrote $versionTxtPath ($version)"
} else {
    Write-Host "generate_version: version.txt up to date ($version)"
}
