name: Build

on:
  push:
    branches: ["**"]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Build Release Win32
        run: msbuild FlowX.sln /p:Configuration=Release /p:Platform=Win32 /m /v:minimal
